### ISSUE TITLE
mapa mental

### ISSUE THREAD

**Issue by carlos0716c** [SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-carlos0716c#1]
[mapa mental.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-carlos0716c/files/14514500/mapa.mental.pdf)

**Comment by MAB288** [comment]
18 de 20

**Comment by josealfredo79** [comment]
@carlos0716c Falta mas informacion... por favor...
